# Dropzone Action Info
# Name: Memobird
# Description: Send to Memobird Printer
# Handles: Files, Text
# Creator: Just4test
# URL: https://github.com/Just4test/Memobird.dzbundle
# Events: Dragged, Clicked
# OptionsNIB: UsernameAPIKey
# KeyModifiers: Command, Option, Control, Shift
# SkipConfig: Yes
# RunsSandboxed: Yes
# Version: 1.0
# MinDropzoneVersion: 3.5
# PythonPath: /usr/local/bin/python3


import sys
if not ('packages' in sys.path):
    sys.path.insert(0, 'packages')
if not ('packages.zip' in sys.path):
    sys.path.insert(0, 'packages.zip')



from PIL import Image
from io import BytesIO
from base64 import b64encode

DEVICE_WIDTH = 384

class Paper:
    
    def __init__(self):
        self.contents = []
        
    def add_txt(self, txt):
        self.contents.append(('T', txt))
        
    def add_img_data(self, img):
        # 图片宽度最大支持384。支持黑白图（色深1位），并且这个傻逼玩意打出来的图片是上下颠倒的。
        img = img.transpose(Image.FLIP_TOP_BOTTOM)
        width, height = img.size
        if width > DEVICE_WIDTH:
            new_height = int(height * DEVICE_WIDTH / width)
            img = img.resize((DEVICE_WIDTH, new_height), Image.BILINEAR)
        img = img.convert('1')
        bmp_data = BytesIO()
        img.save(bmp_data, 'BMP')
        #文本和图片之间需要有一个换行，否则会有问题
        if len(self.contents) > 0 and self.contents[-1][0] == 'T' and self.contents[-1][1][-1] != '\n': 
            self.contents[-1][1] += '\n'
        self.contents.append(('P', bmp_data.getvalue()))
        
    def add_img_file(self, path):
        self.add_img_data(Image.open(path))
        
    def encode(self):
        def encodeone(v):
            if v[0] == 'T':
                return 'T:' + b64encode(c[1].encode('gbk')).decode('ascii'))
            elif v[0] == 'P':
                return 'P:' + b64encode(c[1]).decode('ascii'))
                
        return '|'.join([encodeone(c) for c in self.contents])


import os
MEMOBIRD_ACCESS_KEY = '539d2e325c1744a28bcf232e0c651993'
MEMOBIRD_DEVICE_ID = os.environ.get('username')
MEMOBIRD_USER_ID = os.environ.get('USER_ID')
CLOUDCONVERT_KEY = os.environ.get('api_key')

import requests
import time


def get_userid(access_key, device_id):
    temp = os.environ.get('memobird_userid', '').split(':')
    if len(temp) == 2 and temp[0] == device_id:
        return temp[1]
        
    try:
        response = requests.post(
            url="http://open.memobird.cn/home/setuserbind",
            data={
                'ak': access_key,
                'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'),
                'memobirdID': device_id,
            },
        )
        if response.status_code != 200 or response.json().get('showapi_res_code') != 1:
            dz.error('Can\'t bind user', 'Server response:\n{}'.format(response.text))
        user_id = response.json()['showapi_userid'];
        dz.save_value('memobird_userid', '{}:{}'.format(device_id, user_id))
        return user_id
    except requests.exceptions.RequestException:
        dz.error('Can\'t bind user', 'HTTP Request failed.')
        
def clean_userid():
    dz.save_value('memobird_userid', '')


def print_paper(access_key, device_id, user_id, data):
    try:
        response = requests.post(
            url="http://open.memobird.cn/home/printpaper",
            data={
                'ak': access_key,
                'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'),
                'memobirdID': device_id,
                'userID': user_id,
                'printcontent': data,
            },
        )
        if response.status_code != 200 or response.json().get('showapi_res_code') != 1:
            clean_userid()
            dz.error('Can\'t print note', 'Server response:\n{}'.format(response.text))
            
        return response.json()['printcontentid'];
    except requests.exceptions.RequestException:
        dz.error('Can\'t print note', 'HTTP Request failed.')
    

def dragged():
    dz.begin('Binding device...')
    user_id = get_userid(MEMOBIRD_ACCESS_KEY, MEMOBIRD_DEVICE_ID)
    
    dz.begin('Creating paper data...')
    dragged_type = os.environ['dragged_type']
    paper = Paper()
    if dragged_type == 'text':
        for item in items:
            paper.add_txt(item)
    else:
        def get_extname(path):
            temp = os.path.basename(path).split('.')
            if len(temp) > 1:
                return temp[-1].lower()
            else:
                return None
        for path in items:
            if not os.path.isfile(path):
                dz.error('Error', '{} is not a file.'.format(path))
            extname = get_extname(path)
            if extname in ['bmp', 'jpg', 'jpeg', 'png']:
                paper.add_img_file(path)
            elif extname in ['txt', 'md']:
                paper.add_txt(open(path).read())
            else:
                dz.error('Error', '{} Can\'t be print.'.format(path))
                
    
    dz.begin("Sending paper...")
    print(paper.encode())
    paper_id = print_paper(MEMOBIRD_ACCESS_KEY, MEMOBIRD_DEVICE_ID, user_id, paper.encode())
    dz.finish("Task Complete")

    # You should always call dz.url or dz.text last in your script. The below dz.text line places text on the clipboard.
    # If you don't want to place anything on the clipboard you should still call dz.url(false)
#    dz.text("Here's some output which will be placed on the clipboard")

def clicked():
    print(dir(dz))
    user_id = get_userid(MEMOBIRD_ACCESS_KEY, MEMOBIRD_DEVICE_ID)
    note_id = print_note(MEMOBIRD_ACCESS_KEY, MEMOBIRD_DEVICE_ID, user_id, 'P:Qk0+SAAAAAAAAD4AAAAoAAAAgAEAAIABAAABAAEAAAAAAABIAADDDgAAww4AAAIAAAACAAAAAAAAAP////+221tqrbVqqn///7aqqQAAAAASgiIgAAAAqqqqqr/////////////////////////bbW2ttVutq3/WqtttVKqqqACqUUlKkkiIqq0lVVqqqqqrWtbbbbW222222222221qtaq21uy2qn/9/22qqoQAAghJRCQhAAICqqqqqnf////////+++//99////////+tVrWqq1bVan7X1dVVVVFVIEKlIpKISSAgqlVUqp7bbbba1rVXrr1VXXaqqrbbbbbW6tbWqrVaqz/+/vbVUiQACgEVSSRCgAiElVaSqrv3///////9//f///////+///97W1ta21ttqn/bq1tVVUlVQApUokkQEkARVpVVVV69VVrWta3fa39267W7u6r1qtaq1WrWquqqqr/3/eqtVKIAEgVSkSBFQARAqlaqVavv//////91/9Xfvv/u7v/f//+3W1a1q1XW1T7dV1tqShCkgFCVSIoQBJECq1VSqq9222ta1rf/tv/799a///d9vtvarVta2rZqqn/3/e2qqaoIKQqkpEBCIAAIpUqqqrbf//7///1bf7a2vb/1tt/36/5W6tWrVVq1VT+/a1VVVESigCUSkpIQhIQhVStVVVv1VVfWta//1f//7/bf//re/2/tVWraqutW1X7t/vaqq1EIJJSqSACEECCBSqqpKq9f//39//tq/1tbet/9q2/7t/tbW1attq2qqr/7q6tVVJRCAFKSpIogQQIIqqWqqtX7bbdfrW//t/3/3/q3//7f/a/tbbW1VVVtqj+v/vraqlKRVSpJICAEBBABVVVVSq9v3//1//qt/a+1dr/+2rf23/1Wqq1W1Xa1a339a6tVJUhIAJKqiQJBEECRRVWqqqv69VVva1//Xvv//+u3//2/9W+7atbbVqrWqj/X9tqqqiUlKUkSQBAQQQQEqqTVKVVfv//9//br996trb79bdftX/vVrVqqtV1VVV9+3e2qqVSQBCqoEQSCBABApVVqpVf17ba3rX++3ff///fX/37//t9tVtWq1aqttT/b71VVKooKoSkSREAIICQJUpKtVVlfd//9/9X39121at7/V/e26/u2tVrbVrbW1X3vdfaqqSFAFEqgABAghIEgq1VqlVV7vVWva399f/////u7/b7/v2/a221VVVq1VT+73qrVSkoqgCQEIgKAEAgCRVW1Uqre7//7/+3X2tattr/u7+/b/f1rVabdtWtWqp/e991UqRCEKpKAgIgEgQAIsqSqqq03u21urX//f////+r/vXt+17etarVqqq1arXd3urWqlUUSgAgSEgAQBCJAkpValVUt7//7/9a16221Vb+q99/r/v+1rVatVtWrVR/t7eqtVJBIFKAAACEAQAAEVVVq1Kqfeqtfa3//v77///b/33r/b9vWtarW61rVar3/d11qSiUSQAEgiAQCEREgoVK1UpUF3//3/+tb7ffbu3/u+++3+35qqtVatW1aqz+33eqqqUJBFIQEIQBIBAQCVKqtVVVXdtq9Wr/+v23279a73v79v++21rbVVVWrVV79drWqVRQoQgAAACAAgEAQUqlVVVUB3f/v//Vr9f9f/b//d7ff7burWqtbbaqtWr/f7dqSkkKFECBJBAkQEQEBVKVtVKrJd1W7a3//f7f7X/W3/f31f/7da1qtqq1qqpr1u2pSSSkgRIIAIIACABBIIlU2qpVBf//v39tb1v1v9X/9X29f1WtqrWq1W1Wq1V+/7tVJVUSVEQgAgARARAQAVKqqqlVIqtq9eu/+/6/9v9tX9/v9//+rVarVbWq1VR72u20qSJJAQiBIBCAIEIAiKVK21VKiP7/3772rtftX7f/+/a9vd2+1aq1bVVrW1Vff7bWkpSEqCAACEIEBABEAUilbVVVAC+t9vff//2/+v1W7r/373fvbWrVqtaqqqV76ttVSFIpAoUEAQAQAAgAIKJVVVUqpTr/X9262rf1v9f/v+t+/f75VraqtVq1VaJda+1qQolEqCAQkABAgIERAJSUuqqlQE/V+vfv//7f63919v/bt7e/atqtVq2qrVRt1rVVVCASIgkAABIBIBAABEJS1qlVEgt/b769q1v2/+3ff7b//v7ttqtVtdVVtVJfV+1VUQlBEURACQAAkAJEIKlKu1ZUwKXt++33//6/rX/71f+219v+q1Vq1m1Wqqoq03VJVFQUpCAEgCAEIEAAgFIq1WqqpALfrr++tavt/9Vvf63/vv9u2rWtW1bZVVVVq6wqlQJBCRUQIISBQggQAkiVW6qVEJL1/+vt//+/a3/97v9q+9v7VVq1qrVWrVUq0vdEUlQIoIAAiAAIkACACCUlbVVVQgFfVX6/rW31/+7Xu9v/737dbutWrVqqqqpcU6qpSQlCCikiAQgBQAAEgFCUttVVUFR3/9v2//9vrXv+/363fe/2sy1VatW1VaqOq/tSKkIooQQABCAAgBIQAColW1VSUQAdbf7f21X9/99v2+/937tfXbWqrVaqqqpuUq1UpKiEFFCEkAAiAAAAIiEVarVKqAVP/1f1f/+3a3b6/vtv9v/9pVa1t2qqrVVLitWqEgIhQQIAAAIAEEBBACpKrdVVUFAVq/1f6t3v//+/q6/7f9ru2rVaqbVVVWpmoSqlSVCUEkgoASAAAAIEBBSFVqqqqQEG/rf7f/d6tavr//2v23++rarVVqrVVZVzSkqohEoBQAECRARAAAgAEJEpbatVUAhR2/7f21/f//6+2t99/+321rararVaqqqwoRKmUiCoJURAAAAIAgAgQBoFNtVSlIIFftf2//r3Wrf3//X3Vb++tVVtratqqqpclKVRCRUEgBAQCEEAACACAAilW2qqqCBAq/19qt+9//29Vr+///b21bWqtVVVVVV9QBBKUIJQQIEEIQggQAIIAkoSqqqqqgkUf1/X//bvttfv/+727t/erVa1VW1VVVV+JUUAhFACEiBAhACAAIhASAqFW2qqqkABFvX0u1+7+/77bbvfu/t+tWqqqqrVVqU6iBCoAAqQQAoQABIIAgABAAoiraq1VAkkW98S3/X+r2+v//97/2/u1rWtq1Vaqqp9hUQCISAAAIBEEkAgCCQIAISSqrVVVSAAB3qFKt9r/fr9tbfu1/t6q1a2qqqqlVK7oAKRBASqRBEAAAEBAIElIhUFVtWqqgSSle4JS3v/b1/f3/2//V/e2trVWtbSpVV3qqgEQAAAAAQoiggQAigACAKhK1VVVRAAAvgEpK63+/b1e1/2t/r+qqtVqqqtVKk3oABAEASIIRACAKECIISVIKoKrbVVVQJJIVxCEqv9Xt+/7/W//2/W1tVtVVqqqqVe1UERRJAhCACQAgBIBFACCgKhVVVVVUgACLAJVJVX9/vtvb/rW/7+q22q1qrVVLJr6BQEAAEAAAIkIAkAQQpUoKVJVu1VVQCUhFkEIlK+3W6/9+2//tu+tVatWqqqqkqfskCAEkAkBEgAgSABBKCACgkCVVVqqpIAIRARCUpL//v23r/62//u2rVraq1VSSkr2BIhAAkAIACSBARIABQqoKLRVbatVUAiCAQApCVVW197+/bf/226q1WtVVW1JKquVSAIBKAQgIAgAEAAIqKBChEkqtqqqoSIgSAkARCSt/ffX3+21f/+rba1qqqqqkJfpQSAIASAAASEQBJCABAqQUpIq1VVVVAAJAEBKIpJTb1299r//6re1VVVWq1UqSke3UAiARACACAhCQAIEqVAKCEhKrVVqqBEgJAIAiEkqu//3X/atv/2qtraq1VVFJSL9RIARABIAQSIACIgQEIVBUiQpVqqqoUQCAAgiAiSSTurf+3//+7et2tttVVVRUJf1UAIAEIAABAggACACpSiUJJElatVVWABIQSAAKIJJU3/639W23v+1VWqqqqqsikNdtFBAAgAIEEKIRIBICAQhAkSVW1aqpBEBEACIgCklKVbf9X//99vVWq1VVVVSUhW22QAEQBAAAQAiAAIAoqkIqJIlVVVVVIQQAAgABQCSqq/23+2rXv5W1bbtqqqqqUKragSAAAEASAkIFIgKEASiBAkSqqqqqBBCRKEAECQISlVf+7//+6u1bWs1VVaqRCVaqoAQCIQhAIBAQAAgiqAIoqCklVVVVQEAAAAkgIFCkqv7bva63//XqrWqqtqqqpKlVVBBIAAAEgISAkECIBVCEAoSVVVVVEQSIAiAAAgQSSbv39/v9t1attqrVVVVKEdVUkIAACIAACBACAgQioQRRKFJSqqqqhBAgiIABAEKJKm9e3t+3/eqqqttVVVVSxPEiSgIBICIIQQSgQCEIFEIAQQkpVSqpAEIAAgkgERAipH37+/b+3+1rW1VVVVVJEKwAACBIAgAhACAJEIQigilSBFCFEqqqogCECSAEAAJIEi+/b1/b63WtVVVVVVVUpKoAJQAAAIAAAIUgBBCIUQAAgQpSSKqqiBIQRJUgAAACqDvt/ft/f9a1ba1qqqqiiNSRAAiCSCEEJAAAkAICBFVUKFEJJSVVQIAABUCAiAggBJ6/V7/W2uqrVWqqqqpKYtAIAEAQAQQBABKSASAokQABAgRSUpKqohEgCCpUIICEqDv1/ur//7VVVVVVVVVREGEAKQECpAAgAIAASAkABCVEQKkICElVSEQBBZUSggAAAF9v2/+1tt222qqqqqqqpQSEABBIAEAEgCSoASBFQQIQChCipSSqoABIEkikUCQBIjv+/27//+rVVW21VVVIUJUgpEIAkQAAIAACUAQQFFFCgIQQQJJVUiIABKUSipCQCL63rfvbVa1aq1VVKqpVCiCAAQBIAAEJAlJIAkECQQoIJFKlKgVVIIggChKpJIoEQGv9/79//+qrbWqqqVKkoQRJSAgBAAgAAACAkBBICAAggQBAgKEqqACFIUhEklFSEL9va2vtba1tVVVVVVVSFEAgACFABEAJIBISAEUBIlUCKKqIKAqVUkQQClUqVSSpSHv7//7f//WqtVrUqqqJQREEkgQIQAAgAIBASQAkBARIggEigkFVUBBAhIKRIpUKoW9ettv22tarVqtVVUlVKEAAAJACAAACSBAJABCAkKECJKoIIAolSQEEElRKlEikVP33/79//6q1atVVSCUkkgAkhAEgBEQAAASgJEQSBBQhAhCiiSFKqiQQSREgSSVSkN+9qvfVVvVarVVVUoiqSIAAIJAAgAAkQJACAQBAkQCKVKQAIAoVVACCBKSVJVIpSXb3/91//9trVVqqoEIFIgkkggISEAABFACQSAkIAFQEAQFUhISSqUoIIgkkkhSEof3e3f/u7a1Va2tVKyhAiIAAECBAABAAAAgBAIAiSQEpVCgAEBBKlABBCVJJSUlVEa/791W7v+q2rVVVRJEIUiQiQQgAggAQACEkBBBAAFQiAQKigEUkQkkQJAQiJKRIqvtff///9W1VVVVUqkQCAAEABCIICAIEkgAAIEIJVQCUqEgAIhCSqhAEiVFJEhKlQ9/21bbW3/W1qrVSRABAVJQRAICCIAgAAAAiAQBAAFBABRKUgEUgJUVQEIiEpKQSKvbf////+5bWrVVVEVUBAAFAQgIgAAAAAQSIEAgFKgUqoEAACRIKhBACRSUoEklJU7/7bVq1XuqqtaqqqAAQFJACEBAEACACCAAAQEEgQVBACRVFIESgUqSQEBACpJJUh+1v////9/aqqqqqpqiAAAVIQkAQQAAIQCARAgQJCAEVIEAQAhAKCghEioVUEQkCVv/6q2tt3ZrbVVVUEiQEiCAgCASAEICAAQAAAECAIVRABRUBIKqAlKIAIFABRFCpL6tf////f+qq1rVChUIgAgSAoRABAAAACAIkERIlBAEVQABICQApKRFVCgqoIkUUlf/3drar7a1VWtVZYJSAEEBSBEBIIAAAQEAAgAAASSRACVUCQlSCFEQAQUAFERCiX2193/3+/9baqqqlKiICCBIIQAEAAARBAAACAEiSAAESgABQEAAQoSKSKiqgiIoIl//f+tffqvVVqqqpSIiQIQCgIgQBACAACSQgCAIBKSQEVSoCRVJESVAEgIAKREFEXVb1b/71/5qq1VVUpSIAABQiCJAEIIAIAAAIQRAIAACgAASQAAARIgqiKikgIigil/+/3be/buttVaqSEgFBFEEoQAAQAACAICEBAARFUlQSSqgBKSUEBVAUgQIKiQUUP2rt993t++1VqqqpQJQkAABAIkAAAAAQhIgAAEEQAAKAEAJIAABRSIqIVFCgIKCBVf//fv9/v3W2qqqkFAFAIpQSgABBAAIAAAAQSBAEiVAkhSgBSpIEElEiggQJChRUL7dXrbXW7dbVVVVSgKQQgAFIEhIIAgAgAQkCAQSSIASAIAKQAACQiQRJKKEgQIICvv39////v+qqtVVUpABEEkAQgEAgEBAAICAAABAAAqIIFKgEJKgERBEERQiFFClQK9e3a1a19W1VVWqRECgAgBRCEACAAACQggISkERJIBBBQAEhAgJREQRSKEQQQQAKv37/////b+ttqqqqQoISEUAQQiQAAAICABBAAhEECoUAElQAKAgEREEBQiFEElVAN9vatbbb/u1VVVVJEAhACAEVEEAhAAgQAIAEAEIQIFAQgECSASEhERQqKUgBQAAqvX9////+2+qqqqqqBEEEIJBAAACAACAEBAkBQBBCBQSEVSQAqAAIRECBRASUCqUAX+3trVqr92trVVVUoRQAiAIQpIAAAABAEAAoCIkQkJARAIhKAkihEAIqKVAgkAhVdb9/////X+1VVqqqEAAIAkgEAEAACAACQEiAQBAECiSAQkEAoAIEApAEhIUEAkEAX+vVa2t3+tWq1VVRRKkAKABJVQQAAAAIAQICAEVRIQAiCRAqCkAQUAlRIiBBSBRKev7////dv6q2qqqqIAQJASEAAAAAgIIgAAAABBAAFFQIQECAkAiBBESUEJUUEUEA36+221r/6+1VVVVJFSEAFAgVSACAAAAARBEhQISUggEgFQgEBSAIIBEhRQBAhBBUdvr///+1futaqqqqgBQAgKBAABAABAgBAAAEAFEAKJACQKJAoAJBAUAKEKoIIIUB39/bVW3/26qqqqlIVIIkKAIFQIAAIAAAIEEQCQRCRASQCgASCQgQCARAigFFCRAke3b3//9t/+1VVVVVAikBAogJAgACACBJBAQAQKEQESACQKSAREEEgBAIQKggQESJ79+9bav/VtW2qqqqUARAoCBECAgAAQAAEJBAAQgAiApIEgARIBBQIkBCKgUSFBAg+vrv//6r/61VVVVJCqIECgEJACAACAAEgAABEEJIJIAAgCJAAkUEAAEQkVCIgUKFr7f7Vtv+2tWrVqqkQAkCoJAEAAAQQAEgAFUkApABECJEEkgEkJAiSAQCCgpCJAgR/f6v/393/+1VVVUqKqSRCgIgIgAAAEAKRAAAAARASggQAACAAkoIgRBIpKEokSJFb1v9te3da2ttVVKpABIEQEAIgAAAAggAAAJAQqAEkKABJUIlCSSiEAEiERQFBECC+/e3/7///9WraqqkpUlKKgiACIAAiACRJJAIABIBJASICAgAIJIQgERJSkFQURQrrt79W+q2ra1VVVSSACQRAEAkAAAAACAEAAEgEUBUEiAgQkEQBCSlIgESIJQFJEEC+/vf/r/7/+q2qqqolRKIqQSAQAAEAAAgVQQBABECiIICEQBEgUkISBBAigKQgQhL3171q/dvtVVVVUlCAKEkACAABAAAAISJABBIAUAQUhBIRAkQFBJSAAIIIVBAKkUTdve//t39/+2qtKSoqhSSoBIREAAgRBAAJIAABARKCIEACIJBAUSIkIAiSAoKACBH393tb/9Xbeq21lUEAKIgiQAAAAAAAAAqgASSkEABUgRCoiAEBBEiAhSABUCgqpUK+39/+qv//2rVVRKpKAlKACgAACAAAISAJSAAABIqAECQCAqQEKQIAAAEkCoUAABHt+vVr/7tV9VWqqiiAqQgkACJAAAAIBAVAAISAQAAqRICgQAAAgCRIKQQJUFCqqoW/X7//be//W2qqoUUqCKKBIAAIACCBEIAKIhAkEioEACIJEIgkKIEBABBAJQoAAFPr9u2t/31t+q1VVSgAUkgQAgQAQAAAACpAAAIBAICSoQlAAAIAgiggSgAUiKFVVQK+37//Vdf/tVVqikVUhIKECBCAAAAEUoARCUigKAIIBCICQkASEQEIEAECJRQAAFX39fVr//7W+3WqpTQBIighIEAAAAAAgApEIAAEAhBFEIgQAAiASkRCoJAAiIKqlQe9X1/e21v/2q1VUUlUKQKIAQIIAIhCCSAQgCVBIIEQgAEBBAIBAAApAASkRVQAICLv+/t7//61daqqpKQBBKgghAgAgAAAQAlCBIAIChBKAiQgIBAIKBKUBAABECKqhI/7bt/vVWv/6rVVSRKoUgVEAAAAAAAJBKAIEAqCgEQASIACAEAAgoBAIKqkJUhAIRNf+/V9//+tu1VVUEgFCJQAIECAABAgIAVAggBAIiCSABEAAQQAACqAAAAAgiUqiE/1X1/Xtq3/+tqqqgKgIglIhAgAAQEBCSASEEoUiJIBSgQSRBAACIQiBISUEVCIJSVf9ft+//9q21VVUVAJKJQAASAAAAAAABKACgFAIkCoASAAAAACQClIQBABBApSiJf7b7/t1bX/+rVqrAqEQhEiEAACAAAERIhAACQFCIgFKAAAACAgAkUgAEEkQVEJJEre/eq/f/9bWqqtVUAhKIgIgkEICEkAACIIlIEgUgKgBQkSAAAACJKVVQQAFESkkp/3r3/37Vf/+tbVVSoKhCqAAAQAAAAhEpEgABQKgSgSUAAAAkAAIEhKABAKgSkSSEq7+9bdf/1q2qqqqslRURBUkoAAAQSEAECAAkCgVAKAAJIgIAACAgEApAAgKBJJJT/uvv/31bf/+1q1bSpMJKqAAQAAACAASCQCUIIFAqgoqgAAAAIgQCQQAECBAqQkkJbd67Ve//2tWqtVValSkkkCSEgQAAgQAoBABBBIqASAABSACSAAAAAAAAQAUAlIRV+3vv/7tq//+2qtVVUpSSoogQBACSBBECkIkISCVVACKAAIgAAAAAACJAABBUIikir+762+//rW2qrVVVVEJVUEKEEAIAEAREQAIhApIAlQEkogAAAJAAEgARAQICiUSV/b+vvr1b//9q1VWqqplKipBAQAAUgICBAiCAEFSqAAQAgAFIAAASQABAJAFQUilFr3X97ff+tautVqq1VEqkQSUUAAhAAhIQkAolRRIgoSCQAAQAAEBAACIEACAKhJQrdd9bf72r//61WtVVVaqSlICAAAAAEABEICFAAKSUBAACkBAAiBIEiIAQoAKkIEKT3/b/1u/+1rdVqqqqqlVUAioiAiCUgISAgQQKlShCkIRAAgBAAAAgAABAAQARSiqm+r3V/frb//21aqtVVVUpUoSQoAAgAhAiJBKhIJKQACEIQCAEAUqAAAQEkBBKIREVr+9/X1//Wq+qq2qrVVVQBCkkCAUIIACIAAkEikREgggAEAEQBAAoSAAAAAEBFIpKvbvt9far//u2tVVtVVVKkUSSoJBSCAIAkFSSISkACEACAgQAACqAAEAQlEAUgkClVu6/b73+1b6q1VVVVVSgJClVAACAQIgEAQIEipIpIBCIQEAAQIAAAACCAAgAUCoSqrfr/e+3/+u1VVVVVVKVQpJQhAIpAgBBJCpJAKCAAUQACAAkBAEACAQAVQAiCoFJVa1+r3r9Wr+tqtaqqqqoKkSEEEhAECIQAFQEKgoEhABAAACAACQRAQACAASAgFQkutvb+9/X//a2tqqq1VVKqShQAAEIBICCSQkohUCgIJURIQAAgIAAEAAIKlAEJQlKj29+3vb+1t+q1WrVVUpVSqKlQiRCkAgIAFBCISoFAiAEABAQAAgAAhAggQIAgFIla7XX91+r//W1WqqqqlVJKJSQCIAkBIEgookoFIBAIIkgBAEAAABAQEAACEAQEgSSqtv9XfX/Wr+ra1qqqqqqplJ6QAqAQCQCAFIBQigiCAAAQEAEiAAEAQECQpECCFFJW263979t9+21rWqqqqqqqUlaACBSEgCIioCoFIIIgSqSAQAQAAAQCCQAIERAQgQlVXfu3u3ffv+tVarVVVVUqqptEgQAgKQAQSoiQSCgJAAAEAIAAACBIIBJCiAACJFIrqq7979116u12qqqqqqlVSVUAJFSFAJChECIKAgBAEiIhAACCAAKiBQAIJUkgAIlK7/+vev//f6qqrVVVVVVKqlogAIAAkgQERSigqBESAIiEBAIIAIgVQEgCECAEqiSVWWr736tW1u21VVtaqpVUlTSCACoCAJChKIQKAIQASAAAICAAIAKpVAJQhQgAAIJFtt/e9v///+rWtWqlUqqqqVoAUhAgpQQUhFFARAAkAkSQgAAAghBEqqkEKKJAShFSb3t3X7VqtW6q1qqqqqqqpSgIAESAAEFBUioVABAAIBACAAQgCAUqUlSpAggJAKSpWq7d9f///9VtVVVVVVVSVVSABAACpRApJQRAEkJIiQIIAIACAACSiSJCJEIACQoUr7v3v1tbVutVWqqqqqqVVKgAkJIIAQUCkKgJAAAAAECAAAEAQAhVKpUQgRRAAEFKVd7e7ff//622qqqqpVVVSiQQAACAEkAhShJAQAgkJAkAAAAgECKUpEiKVCEJIRRSqqu7v32q2uqq1atVVVKpKpAABIgBQSEIIIQSEkIAgSASAACCAAFCqSVQAgQAAAIJW/bu9df/99WtWqyqqqqVVUBAACJEBQQDSiEAgABQAAQAIAgARAQQRJIlUUiQCElSVK373362vu1WqqtVVVVUpCIBIgAAEUBIkEgkJAQCCABAgkEgEABBKlSIBAICQABEqqte9+3766tqtVSqqqqqqogAAEQgQhABIQICCBAIASICAAAIAJAAESIiUVCgBBVSSqrvvX+vftWq1VaqqqUqqkAACQEJAUEQiChQgoBAQAAAAAJAQgEIBIiJBAQEAQA1Kqt679X92+1bVVlVVVSlUoAAQBBAEIACIoQKIAEABBAIBBAACAQCIAAiIUEgEEUbqq2vuv9Xf2qqqtVVVVVUlSkSBAQSRCQggBEAiQAJAIIgIESQACFAgECBCBQBARBWqtba77b/1dVqtVWqqqqqqIAAIUFAAQAIKQokAEgAEiAEhBIgIQAoBAQIokCUAAEb91t/u3va/6qtqqqqqlVVVRSEhBAJEECigKSBUQCQAQpAIQkIgBUhUBAERBIAQEgtXbWr/99/tta1VqqqqqqpSEogEAUgQhIRChIkBAACVKApSCCkBECUCgAREUBJBBCLtu79VXXV/+tVatVVVVKlKhCJBJAEAEBEQEkAECQIBRIAAIIQAASgBIhAQAkAAIRVf7tX/99/VW1rVVVVVUqqpKUAUQKRJAgRASSpQIBAUKRFSAilEABKkSABCSAkQBIN1e3ttvvt/9WtVqqqqqqqkhJUJFBAAICElBUABAABBJIQIgESQgEkAAQAAASBBEBGvr6+766/tu1VqqtVVVVVVUgBSQqKSBAiAIikABEEEQiKAEBJCCASoSKQSRAkIAorVevXuvv1/5W1VVVVSqqqQCIgJKRQAgUJUlIBIkAgAEBSqBAEoACqRAgCAEJAgAIS6366779vVe1aqqqqqpVVWoSKklKlSIBKAQlUAAAARBIJAQVSBQQJEEEIBAgSAUkJvUvve+v9/1Vqq1VVVVSkoSEASQkoACUhVKQAkAQBAQSkqAApUCAlRQRAAIFAUAEk1/a7rr6vbetVqqqqqVVVVBRSlKSWpQCKClKoAkCICKkgEJJFJQAVUFAAgCQJBBKFWq1d++/7/21tVVVVSqqVKoEIShEpEKUkpIiCgAAAIkIVRAASkJCAioJQEgBAEECSV/vvXvreq9VVarVVVVVSpFRCoUAGoECRUkUoEJAABSlIAQpISEQKUSgEAEQUQQShKq6176/3/urbVVVVVSqqlSIoFAkpijqkSSCFAABCEoolICAFUhAhBEKRIAEhCAEolvf+uvtdt5atVaqqqVSUqpVFQSBE0JBIpBUoRKIISFFUiIEgCUIAqRAAABAEBEhES11X7773ferVaqqqlVKqqUqQKAUqpEqiIqJCABAABQQSIAABUBAEEESqlIBIQgKlJbf6uuvd11tWqrVVVVVVVK0ighCV0pAokAiRIUogkKCEggiIFURQBRIAAAICEIEwiNqv379//eqqtVVVVVVJJRaIII1Z1SSUSqQICAACAgghKAABACECQESgqiAkgiSuIm/66vXqt5Vtq1VVVVVVVVvCigUn9JJKISKlQEkQQBUEQEJIVRAgCREIAIAACIFTiVVfv99//euqtVVVVVUqqU0pIFSxdUghFJQQAQBFEFwACQCCBIREAECiCRESoCha5C3q1XfW12y2qqqqqqSpJS+ECoq2rSUURUKFJBEAAKQJIAgQqSESQgoQQEAAAkIquVa3f91/v9WqrVqqqpVVVKqSoSkTVUhBEChQAEAVQlEABCCEJBAAACCkAQgKkBFLbAna1Xva9WqrVVVVVVVKqpckFJSltSEISpEEkQREGAQSIQAhSUpUiIgRJCIgQkQFd1Vf/99/3+ttWqq2pKqpKq6QikoiqoQSJIRRBBEQFEAAFAkEJSAAAAKkAAgCEBLRFSKyqvXre1VVaqqqqqlVVJcKJVSSqSCFSSCEAEABOQCIiKAgkJSlAggIkkIAggKqpIrff1++7+1VVVVVVUqVSq1QUSoJVAQiJEQgoQSkFCQAIRSICkIAACFSABCSUFLUU1K11fbruuqrVVqqqqpSqk4BKpSiqqERSQKKCBAAAgAiBKACpSgSQIAIJQRACQlrXdTff1+/75VtWqqqpJVVKVVUhKoVQBSEkFAgIIIAqEgAkgJQEISACAVSgFCBQAStruqr1fXtfeqqqqqqqqqqqpaCUolKqqFSRQSUgiBKCiCAKSAEhSgRAQAEAgQIFEl226p9f16/121VVrVVVVVJVU0oilIqhAoBICACCAgBUpAJRAkgIkKAQAqiEIJAiQSrbfVW2/f1feq1aqqqqkkqqlSFKokVKVFURIqogkEUJUqkkSAKiBAKCEAJACEiIAK6r1qr7r2/31VVVVVVqVVVSU5SVFJKgkQhEAACKCABEqkSSAJBAopAggKkhIQQCkhv1elde+7rderVVqqqpqqqVSlUooSkVJKIQSkkgQhSSSVVIqgUUEEEIEACIBFIoAEqtrq3rtu936tVqqqqqUpJVVZKlVESAQkiBAAAKCEEhVSoiAFBBRQhBBVIgQAgCpBK6+qte/7ve+yqqtVVVSlVVUqlVCRJVKSIkASRAIQBKJUkIEQAQEEEQQACCEIUIAQBWrq3rqu77uqqq1VWqqqqqSupKpIiAhJSAJAEAgCQEklBAhEgEBRBAEVRIACCioFUte1a9/7uu5VVVVVSqqVKpVWqkUSIqKEgIgAASAoFRSQoEEABAoEIJBAAgSIoACQCXVrvWqv77uqqrVVbVSqqlU+qSiEkAkqVAAEgAAAgEJKEggqESCQigIKUJAAFSQCUVvVV7/6u++raqqqqpKqqalbVURQRVIlASJACIAoAAkkoIIAAAIEAAChBAJCQgkQCqr1uuqv7r2qqqqtVVVUplVepJKFEgiRVAgAAAICSQCRCiCAgKBBEiRAASAACKAFRL2q77/6u/dqq1tVVVSVVUpbUlQoSKRKAUARAggQACQEQAgSKggQAIEqUAkkggqAElb1Wuqv7t2qqqqqqkqqqqlWqQlCIkkSqACAICACAAFRFIQAgCEEigBABEAAKKASSVqrv7/7f7+qqtVVVVVVVVUqlKIpSSRKRSQEAAAASRAEACEkKoAQACEqkAiBAAkBBS71auqu1etVVVVqqqpJKqVaQkiEJJKqkIAQiAIhAEJAkggBAABCJIggAiAgSUREUVa6v7/3/32qqqqqqlKqqpS5KSUhSSlUSiiAARAEBAASIICUShIAgAESpIIAACEBBK2q1e1ardeqqrVVVUpVVVKshIhKJEVTJQAAQAAAIAhAhCoAEIAICiRAAAiSVJREUVd9vrv/+36qqqtqqqqqqqqlKSIQkpVMqKkECASAASEIIQBSRAACAICIkkAAAAEBBCtVa+9qr9tqqqqqqlUlVVVakhFFSSqqkkAgARASRAABFCUAESRBSBAgAAkgSRREIVbdfvu/+verVVVVVUlUqVVUoIggJKqqSRQARAAAAEQIQBBSBEAIAgSSJIAEEAEQihduq67qr72qqrVVVVUqlVVVCkUVVSlVUkCBAAAAEQBACQIASQEEgJAIACSQRJRAJKu1dvu/+29VVVVqqlSqqqra0RCFJVVSCBIICJBEgBECQEikABQAJAJAhIABAAEJCQWvXa71XvW1VVWlVUqpVVtqiERQkqKpUoggAAIAAEAIAgAAAAAVAEgUEApAFRJSFFLbV/vf97+qqqqqqqqVVW1WpRKKVRVVJEKAQgAEEgQASCUQJAAASiECAiAQAEAERQlu3V923etVqrVUqlSqqqq1UEBFSVKokRAECEkQgBCAAIAAAEAJAIQpIIFEkgqoAKQrr+3d936qqqqqqpKqqqvVSgqRJUqlCkUggAAAAEAkAAACAQBApSgAhAQABAAFSiqV1Xd3XdeqqqtVVVVVVVSrQUFMlKVUVRBCARCAIgABJAAgAAgEQFKEACBAASpQBRtEV63d931VVVVVVKqqqqqqqCoiqpKpIkUQEAQCAASIABCAEiABEIghEoIUlAAKqK31Uv93Xdeqqq1SqpVVVVVVBUTUhUqSmShEhKEgABAAAEIAQAJARCUEQAhAAIqkBRavqqvf9/1qqlVKVVSqqqqiUCpJVKRERUUSQBQACIAgiAAEhKgAIJJAgiEABAAJVU319X16vq+qqrVVVVKqq1qpCSUkKpKRKrKpKqJAQAECAAAhIgAEkgkSCAQSISVEFRauvVff6/tVVVVVVJVVVWtUpJSpSlQolUpEBUgAAAAAAQkKSVIAICIAQJBABAIiVU3b1y11fq6qqqqqqqqSqqqSUFVFKaqFSVEpVJKkBBAQEABRFAAAioiIIgEIgRERGpbvfdff1/u1VVVVVVVVSVVVCpKSlVIgKoqSKkAAkECAAAEEokACEAUCgCQAEESIKydb11V2/b+qqlVSVSSqqqqpVEpISpSKqmlJUpQQAAAAgEQiEAhACqBAEICJBQFFGpXtferfVutaqVVVVVVVJVVVIqkmqVRBJSUqqACCAQAQCQAIiQIAIAUkRAQAIAQgVUqv27t1273VVVVVVUqqqqqqlRVSVVIUkqqqpUgARASAIABCQCAEFVCAECCEgRFKLavq7v2avu9aqqqVKlUqkq1VUqSVUpFCSVVRUgAhACABAAARAggAgkEigQIgBEAhKqq/e67v67uq1VVSqqqqqVVSSVVSSkoVKgiKACIEAIAgAAAACIEQCQCQIBCEgAEUXarV3ve1fu5tVVVVVVSlVKqpVJJJNSCAlWUlVQAAFAIACQAAACQAJKkABIIAISRCJqtva93/q7uqqqqVKpKqSqqqpUqqqVRVVSiSAECQAABAQAIAIgACAQCqoAhEhACRO1W1/vaq/v+qqqpUqVVVVVVVKqlVVQISqqpJVQgAVBEECAAIgJAAFKRAAgEQAJAojXrfV7//t9VtVVVVVVVSqrakpJUkpKiJVVUkACIBAEAAIRAgCAAAQQCQIEhBIAKEVUq1+tVV/X+qqqqqpSqqqqqqlUqVVUREqVKQlIRUoQSABAAAAQCECJEEgQIECUAii3bvX///V9VVaqqlKqqqqqqVUqlSqSIiqqqiQlEKSAAAAAAAICAABEQgJASQgBJIZVtb6qq2/b+1VVVUqqqqlVVRKlRKRJEJVUlJKQpSgAEgkQAAhIABIoASAEAgKkAFMqrtf//vt3ZVVVUqqlSVaqpKkqUpVUSiCqpUhKSpQAQABEgCAAAECCSAgRKCAAEoqvq3rVW67d+qqqqqqUqqlJUqSpVFKhAIoSVCKVJKBAACEABAAAEAIoIoJAAgqqgSVS1a+/9/v3W1aqVVVVVVVWqlUlIqkUVSSFUpRSlVEEBIAQAAAgAAiCQCAEoSAACEqrbvV1XV9f9WqqqSSqqqqqpVVSlIShAhESSUKpVUQAEARCAACAgSBQAogQFAKqQRLat1+v9/X6uqqqqqqlVUlVVJSKSVJIUUgFJJVVVRAAAAAIAAACAAIKkABCQQgBACVta+r7fV9v5aqqqqqqqlVWqqpSpAkFBKRIqklUqkAAQQEABAAAAEFAIRAIEIKopAk3Wr+t1/b6uqtVVVVVUqqqpVFJEqSgIRECqSVVVIABACQiAAQQBAgqBEICRCAEAISq1ur/fb2v9VqqVVKpSqqqqpUkqRISAEgSSpIqohIgBAAAACBEEAKAQIggCQqipCJXtb+r19f7WqqpVKpKtVVVVKlShElEpKEJKlVVVIAEAICJIAABQIAUIgAKoIAokAlK22r9fX1d9Wqqq0qqVbqiUqoJKSQQAAhUpUlVSSSAEBAgAgEqABAAgJBABEUSQoAqrb+v19/3aqqqqqqqqq1VVVVSRJFCVUKSqSqqpAApAAAAAAQAkgJSFAAFIgCgKCqBVtX1fbW91VVVVVVVVVWqqqSkkkgIAChKklVVEVJCIkJAkCBUBEAAISQAgUgVEQBUk36/1/9vetWqVKqkqqqpVVVJKSVAooKkpJKqRAQQiAgAAAACoQgUAABKEgKISlIiSVfVfVX16qqqqqSVVVVWqqqkREESCFQVSUqkoSFKUAAgAAERFCEASVAAgEhSiACJKrr/1/9fdVVVKqqqqqlVWqURERREQiCKJSpVFIpBSoEIAIQEoIQQAAIiIgEIJVQqRK9Vfav3uqqqqVVUlVVVVVSqREIRFKokkqqopEAqKlAAhABIRBBEpCAAiKRFQgEBNUr/13691VaqVVSlVUlVVSVBIRSEISQCCVUlEpUEhUiQAAACkUEAAQgKIAEqFVRKl6uq/evu+tqpSqqUqqqqqpUqSEAgCkiQVVKUqSCiUFAAAAAkRBASECCAQpBBQUAQUXV/V363VVVVKUqqqqqqqqqhBSSEgJIJICpVSgoIigJJIASBKURASAIRCAKVKiqFLqrV/df7+qqqqqlSVVVVVSUUUBAgKkSkrUVVUUCgAIAAARASECIIAkgEISApRKBQgtt/V31dVtVVVVUqqqSqqpSiioKJACkSkpFVVSoFSBJEAAAAhREiIAAAhAlEkRUEKq1V/df3+qqqqqqIkpVVVFJIUFAAAgJJVUqqSoCQIgAQiAFVIkQAihBIICASSkpRQLX/V31dtVVVKVVlLVKqqpUlBQSUSKkSSiklKWoAiKEAIEQIlIFIAAQBCgSKpJEEFRVV/dv3aqqqqqSUqqpVUkiSUFABAACkIUiQlJSoAghEAAAiISgSSJAQgJBBIiRSoktvV3dd+tVVVVVVW2qSqSUkioVIICUSlKUkQlJFKAIAgAAABAVAAgECKgIqkUUISJVb/d33VVqqlVVVaVStqqiSQRARBICqURJBESkgAKAkEhCAEKARUAgIQCCAVJCiqkLdV3d9+qqqqqqqpJK2qpVJKkqEEApJKEkURKiVAgSAgAIJAAqIAABAiAopIkUUKqlv/d3XZVVVVVVVUkpVtUgkkJBQgCElRSCiEBUgoAASAAAACQAglIkAIoAUSCJJVVSqr3d922qqqqVVCqq1VVWVSkoEIgiUqARJRUgKEikASIggACEIAAAIiCSAJVCQK1U3+9/XdVVVVVVUqqrVVSSkpSFRAERKSoKqIBVEhIBIAACARAhCUEQgQIEqkAolSrSbXXV92qqtSqqqVVVVVNUqUpSISBKRKClS1QUgUAQCJAAAAAEQBACCKBAICqFEKttN79/XdVaqqqpSqqqqqqqlSUpSAQJESgJKSKIKAhFQAIICCJQkoRIAQkUlIRQSl11XdXV921VVVVKqqtUlUkqqqlEIiCkxJKkpJQlBEEAAkAgAAAAAEEARCABICkVJJa+l39/XdVVVWqqqtXSSVStVUpSiIACKRESlVKIkRAQEAiAQBASoRAEAISQFQCAiSurVuvV92tVVVVVVVqqpUVVVSkqogVVAkqqIkklBAREgCAAAQBAFEQhERAFCBRVJE19q71/XdVVqqqqqqqqVVUqqpKEUEABUBCVSCqAQIEABIIEACQJQIAEQEUgRAIIQpXXre/V922qqqqqlaqqlUVKqqBSigkqKooqqpSqFCQUAAhAAAAAIRSQBRAEIpFClEW103V/bdVVVVVEVLVVSqqVVQoJUIJFQSEVUAVEgQBAEAAQSAAlSEACEEJBCAQoIpLe17/W/2qqqqq1IkVUpZFKqqBKJBCRLEilTVKpUiIEAIkCAJEAIRIggCgIEoEFSSt1qdV9q9W2qqqqqVKqkqVSqggCkQoEkoRUqokSCIgggAAgAAAJCECIIpKCQlCghITu9X/X/WqqqqqqpUqqlRSpUqAFSFFSSEKSqSSkpEEEAgiJAAggoJQBAEAhCAQVIlK7q9V9V9VVVVVVVVqtSqVFSAAAoiQIJQhNJIIREiRAAAIABEAAEgCQShUIAqFAiUV29X/X/WqqqqtVVVVVUhK0qqEAEUmilKIlVSiKSogSgEAlEACFQFICAICCSAAVJJFfWtV9V9W1qq1VVVbaqsqqlQgQjVIQCgCVUkJEklFAEQSAQCAAKIAoklQoAqiAkSS79f/X/aqqqqqqqqtVUqqpUKAAJUClUVVSqSgpCSQUgAAJAIIIgiiAAAKCiAQqSJK2uqr9rtVVVVVVVVVVVVVUlgCAlSgAKgJJJJKAVIhAABEgQAghIEACRVAgIVEBJFC96/9Xe+qrVVqqqqqqpSpSSVISSoVVSVVVUkhVAkIUSEAFAiAASRIgAAUKBARKEpJXdVX93pVVVVVVVVVKqVVVUgBBKlIgEIqqqCUASRFBAACQIICEgAgJEqCRQKIQqEkt2v9Xd+taqqqqqqq1VKqqiVUUqolKiiFUlUiqAoQUAQICEAAAUkEgAAoEEhCFFSiva6v92tVqqqqqUpVVSpSpVIhCVFIhUQtVUhUBSKChSBBQhJAlAJQAkkChAEogUpJV+v1Xf2qWqqqqqqqqqlVVIlKVVSSUKkVUSSKoIUkKAAAEIAEAoiBEACQISQCKkQgPVa/91dVqqqqqqqVaqqpUiQkiUolClBVaqoJFBCBQgESRBUgIQQkASRElECoCLKlT6/qvf2qrVVVVVVSqqqqqUqSVSEQpSSJVKAiQSUoESAAEIBBBElARAEQAQgCpUgRFdV/11dVVaqqqqpK1VVSSiJEiVSlIJIlVSqIlACBRIQhBBUEEgASEJBCVCJIEFKiDt+q/f2raqqqqqVVVVapUokRJIJJSlQVVJICAVUQEgAIUIAQQSqIgAUQAQACSqgQp2r/V1eqqqqqqqqtVVVVKSSkFSqSEVKJUqlQVABFAIiBBASACIBAIUBFKJJQhJKkBb+r/f1VVVVVVVSVVVVUpJIRUkEkhIpEqgQEACUAUgAkIJACQgkSgCQABAgEKlQRS6r9V1eq1tqqqqpVUqqqlUFIFJSSIFUgVbKhAQClAKIAkgJICKIgCRCpUqCBSSiiAV+v/f1tVVVVKqVqqlVSUiolSQhJFSSJCEhIiCQQVACECAEBIgREQEIEAAQoJJQIpbr1V1elqqqpVVVaqqqqlIlCJFMkiJJACqUkIQFBABAQQFAkAKEQAChIKkECUklQAN+//f1arVVVVVVVakUVSqQoqQiSRQskQlKJCJCIIoABEgUAkgiBRQECgBAgCqoCkmrVV1elVa1qqqqtqVVRJSKSUkZJIKSRCQhCQiIhCARABABIAUJUAFQoFUSJVEhQCL9//f1atVVVVVKqpKlKqJlJJCkkFVKkIFKUEIiEQCACQKUClCEgSACCABAQCqYEgFXVV1elqqqqqqqqqpQklUQkkUqSoCqQgAAhRAEgEAAACAJQAIiIASoRSUJFURVQJT9/+/1VVW1VVUqqqVKSUiqSSiSIFZKkCKqKAVRBBAEJAhQAoiUigBEEAgiQClUBABXVXVeqqqqqqqqqlKpKqUSJJJJSgklRIAAgpAIoUIQACEFKCIBIKURRUEIKVUqkJK9/7/1VVq1VVVVVUqSRFKlEqUqAVSqIAgiFCEkBAgACQAQgISoCABKABRCgkKIQgBXVdVeqqtVqqqqqqlJKqkQpRCkqgKlSkEIIQgCkIAAgBSKIhACokggqoAoSJhWACQ9/v/pVWqqqqqqqoqkkpSqiNUqAVVSUIgghIKoAECAAIAhCEJISQAUACUCIkVKkgKXV1V+qqq1VVVVVVUiSKUlUkpJVEkpIiACECgBJBAECgkUogQiBFRCiRBRSSqlAJAb+v+tVaqqqqqqqqSUpSqSCqSVIiSqkIIQQgJIAQIQQCCCEJEIoiAUQIEEIkgqCAJNX6r2qqtVVVVVVUlCKUlJUVJIkRKSShCEAKgCREBAAQopSgAhEIFBJFQikSWTQiAH6v9dVWqqqqqqqqQpRFIlKiqlSklUJIgBEAFAAQgClECUIEUKCigEgQCISJJKCASVf6v1VVVaqqqqq1KEKokqhUkSJKSiiEJIhIQIBAAIABRClBCQoEiSKFIiJUkpgJAHqv1eqqrVVVVVVVVSkFKQqSrUkRJURRACICAgQSJASUEUQgJFBQQBRQQIkFSlIgFB/1f1VWtVVVVKqqiJSohKRKRJJIkpIEUgCoiABAAFAhRBFECAECIoICFERSKViCQVVf1eqrVVVVVVVVZUIiUlKlMqSSSkFQAJQCAAgUAASEEqSQglQgiClIQpKUpIgIAB/q/1VaqqqqqqqqkilJCSkSilBJIRQilCKgQCBAkkIiQBIAIAiKIIQBESRJElQgEkV/VeqqqqqqqqrVVJSUpISoqQqSSqEIAggIEQESABCIlUlRCqIAClKoJIkkqqqBAI+r/1VVVVVVVVVVUkUiEqoFJVBEIQhASKCBAAAASIoiAiQEAACRIUiCRFJKRJQESAL9Veqq2qqqqqqqqSpKyJFUkkoRRKIqAgQgAERSACCJVJCgIIoECCQoEoiRKkoQAlWv/1VbVVVVVVVVVKUkJUpJKSFKKSiAqJEECQAAJIogIkgRBABAopKBSSUkkVUAiAP1VeqpVVVVVVWqqpKTVCEkRJSRQkIoAgQggBFUgCCVSSJEUVESCEgoBJCSSkoiAKFf/pVWqqqqqqqrVEpJSqpJEkIlFJBCkKCCEAQAFRUCKJARBAQIQiUCUkpJJSUAIgn1V+qqtVVVVVVVVSUkpUkkpJSIgkoQBAQIAkBJAIhYkokAUKFREUJQCSkkkKoIgBC/+tVVWqqqqqqqqqiSVSSSCQEiUSFEooAAkAkQSFFFSlBKAhQEBCkFRJKSSpFACITVX2qtSqqqqqq1VUZKlVJIpFRJChQRCCBCAiBFBSSSKIQQiIFSooSgKkhJKkoEIhB/69VqtVVVVVVVVVEhbQkiESUUgKKEIQIQSIQQUpJIpVIKICokFFIVESUqkSkhAEIqvWqq1VVVVVVVVVVKVVJJRJBCKlQhCAgAABFCFEklSCikAoCRQRFApJKQSqUAEAi/79VVVVVVVVVVVVUhOoiSKkURAQiUQkBEkkQRQpSUlYUREAoEKkpUElBLJFKSQiIVdWqrWqqqqqqqqqqqV1JIgSiKVFJBEAAAABFKmSVSQlRKRCFRBJEiqUqkkopAAIBfv9VVVVVVVVVVWqq9CqUiVIREgQkQRJIiSoQgRKilVSkgAggEqEpKBJJSSVUEJAUK1Wqqqqqqqqqqqqpf6pCJASIpKERFAACIAFELVUaUUkSVUJKoApEkqkkJJEiggEAv/9VVaqqqqqqqqqlbetYgqhEERREQKAgClQSqSlkqqShIBAkCqQqSISSkkqVCCREFVWqqqqqq1VVVVVVf72lKAIhSEEREgqEgIKAkqVKihKUlUVJQBFBJKpKSSRJIIARX/9VWqqqqqqqqqqqvet1QqkUBQgESAAQJChKlVUqVMkpIiAkKqSVUkSlVJKkgAIAFVWqq1VVVVVVVaqqd/3WkABBUEJQgqRCAoUSVJSpUlSElUlKgBIkiSkQgkkqhEhFF/9VVWqqqqqrVlVVf2tqqqooBRECKAEIkFJEqqrFSpJSSIAhFUlJUJJKWSSSQQAQTqqqqqqqqqqqqaqqvfbbVSEFUERIBVBCSpSqlUoqKUqUkqqKCCQkSkkqhJJJSBJBB/9VVVVVVVVVVqqq99utaqygBSkEqIoUpFJUqlVVVShJSkBEQpFJJSShUklVIEAEUquqqqqqqqqqqqqqX332qqIVUJRRBSSiK1VK0qqqpKVURSqRKEokqJJKKSUkggIQB/1VVVVVVqqqqqqrf+tVqqqgqlUkqJJJVSqlKqVUUlKFUpRUAiESSkklRJKSqBBBIq+qqrVWqqqqqqqpffbta1SVF7rVVVUkla1arVpTSoppFVKVUUilJISSKSRUoIEEE/pVVVVVtVqq1VVVb222qqpqqtarVVW1VVqqoqWqqmkEoklUBBJIlFJJRJKSUBAQRK+qqqqqqtVVVVVVP/vbVVEtXWttaqqqrbdVWpUUJSVSSSSqoqUSSpUkqSRKiQSBEftVVVVWq1Vaqqqq+27q2qq3q721rVVtdVqqqrTS0pJVKpURCAilISCVEklSUCAQBK2qqqq1VVVVVVVVP/W3VVRa9tVata21q21qqqqqlKkSRFFKIqIQlJZQpJJJSIJEkX9VVVVVVVVVVVVU7t7a1VKvW3ftqrbatbdVVUqVKRVJKqShCBFKVUkmSSUqKAgABOqqVVVVqqqqqqqqf/XtWqk17dyrbVVvXXqaqqpUpVClURUVQqQihCSRJEiSpCCSQF9VVVVWtrVVVVVVXftXaqpetrd2qtuq663VVVWqlJUUJKKpEBKUUpJKkpJJKQIAFXaqqqqqqtVVVVVVf276qqS32+2ttVV1rXaq1UpKUqSplSpEhUiilKkkSEUqlBAkgD1VVVVVVVVqqqqqt/Wtqqpaqrbaq27etttVVVlVSpKESSSqSJIUSQSSpSikSEEAJVeqqqq1VVVVVVVVft/q1alve3ttrVWq27baqqVSqklSpKJJAiSipLJUkoUSpQQkgD1VVVSqqqqqqqqqv/VfVqo11dbWtbb3bXtVVVVMVKopEpUlUUJJEklKSFKqVBCAEpeqqqqrVqq2qqrVW73pWVFbbrt61Vtat9WqrVqyoklKqlKUihSUSSSRJShJJQAJAC5VVVKqqqrVVVVVf/a3qqpu227Wqtbt2r1qqqVKlVJRRIpSQKJCpJJKkoUkkiSASRuqqqqqtVVVVKqqvdvaqqlbtbW1bW2272tVUqqqUkqKKVEpShEpEkkkSFKVSQAkAk9VVVVVVVVaqqqqX31taqVt7t9uq1ttutVqrVRVSqFUpSqVIUpEqSSSpQhSVRIBUBWqqqVVVVaqqqqqv/f2rVRbW3W1ta27bb21VVNSqiwilIhEiiEqBJKpElVJJICQBI9VVVVWqqqqqqqqu3qrtVK37a7a1tvXt2aqqqqVIUKqSVWqUUpBUkoEqSIlUkQEgEuqqqlVVVVVVVVVf93a1VVtWvW3VW69etq1VSpSrTURJIolRCSUqVFqRJSpKoBAKSZVVSVVaqtVqqqqr3btVVRf717aqrXr12taqqmqkopUlVFQkpElBIoRKSJKhJISAAWqqqqqq1VaqlVVXft3qqq1Wqttba69ba1VVVZUqVFFUiqWSEpIqlKlRIkkUkBAkqdVVVVVVVVVVVUqv+7aqqTe7f3bqtvXutWqqqkqlJUpSURJUpElISkUkiSSqoIIABKqtVVVVVVVVVVVX3uttVJrtqttVrV613a6qqrJSklUJKlSRESQlISiVJJVEkgiqSOqqqqq1VWqqqqqvf121qq922222t+veqrK1UoqUSSFVRUpKSklJVJJIkkiSSCAAAlqqqlVVaqqqqqqv9fbWqiutrbba2ra17a1KqrSjKpSkqSFRISSSCkklJKVVIIJCUKtaqq2qqqqqqqqr31taqq329u1VVt3utqtVKlKqUkpSRK0qSklJYSVSSRIkqggQBGqtVVVVVWrVVVVXfbWqqTatq7vra261qtVVVZUpSVKJMkSUJJIklJIpEklSkCEFIpVVVVVa1VVVVVVf/t7tVVvbbtatttve3VqqqlSlJIlUiTJJUklKJUlEoSqJSgRACGqqqqqrVVaqqqqn27VVai7u23t1W3a1a2rVVVKUqlRKqoqkiSQhSCSSFJEqKJASQitVWqqqqqqq1VVW/v+1VVW7ba2tra3btaqqqUqpESUkkVEqJIlKJVJJQkqlVAEAKK1qqlVVVVVVVUqv71TWqS9tttbWtvttWqrUlSklVVKUqiqSklIkkkkqKSRRIiRVAiqtVVaqqqraqrVXve9qqrXW23t61a7W7VVKqqqUkipSSZJISQlSSSSRRJKKlAAASI=')
#    dz.begin(MEMOBIRD_ACCESS_KEY)
#    time.sleep(2)
#    dz.begin(CLOUDCONVERT_KEY)
#    time.sleep(2)
    dz.save_value('USER_ID', None)
    # This method gets called when a user clicks on your action
    dz.finish(note_id)
    dz.url(False)
